export default {
  PRIMARY_COLOR: "#3735AB",
  SECONDARY_COLOR: "#8686A9",
  MEDIUM_COLOR: "#5857AC",
  NORMAL_COLOR: "#FFF",
  LOW_CONTRAST_COLOR: "#C4C4C4",
  FONT_SIZE_SMALL: 20,
  FONT_SIZE_MEDIUM: 23,
  FONT_SIZE_LARGE: 40,
  FONT_SIZE_REGULAR: 28
};
